spring.datasource.url=jdbc:sqlserver://regulus.cotuca.unicamp.br:1433;databaseName=BD25316;encrypt=false
spring.datasource.username=BD25316
spring.datasource.password=BD25316
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true